services:
  hora:
    build: ./docker
    privileged: true
    network_mode: "host"
    environment:
      - DISPLAY=${DISPLAY}  # Set display to host display
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  # X-forwarding for GUI
      - ~/.Xauthority:/root/.Xauthority  # X-authentication
      - .:/code
      - retain:/retain
    tty: true
    stdin_open: true
    security_opt:
      - seccomp:unconfined
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

volumes:
  retain:
